version: '3.8'
services:
  database:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=example=value


volumes:
  db_volume: